services:
  api:
    network_mode: "host"
    build:
      context: .
      dockerfile: Dockerfile.api
    command: ["uvicorn", "backend.app.main:app", "--host", "0.0.0.0", "--port", "8000"]
    env_file: .env
    depends_on:
      - db
      - redis
      - minio
    environment:
      OLLAMA_HOST: "http://127.0.0.1:11434"
    volumes:
      - ./:/app

  worker:
    build:
      context: .
      dockerfile: Dockerfile.api
    command: ["celery", "-A", "backend.app.workers.celery_app:celery_app", "worker", "--loglevel=info"]
    env_file: .env
    depends_on:
      - db
      - redis
      - minio
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./:/app

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000"
    depends_on:
      - api
    environment:
      - VITE_API_URL=http://localhost:8000

  db:
    image: pgvector/pgvector:pg16
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  minio:
    image: minio/minio:RELEASE.2024-08-03T04-33-23Z
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: ["server", "/data", "--console-address", ":9001"]
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio-data:/data

volumes:
  pgdata:
  minio-data:
